"""API tests — uses FastAPI TestClient with a mocked Bot."""

from __future__ import annotations

from unittest.mock import AsyncMock, MagicMock

import pytest
from fastapi.testclient import TestClient

from ivo.adapters.base import ModelInfo
from ivo.api import build_app
from ivo.bot import build_catalog
from ivo.bot.handlers import BotContext
from ivo.config import (
    APIConfig,
    Config,
    DefaultsConfig,
    LoggingConfig,
    SessionConfig,
    TelegramConfig,
)
from ivo.session import SessionStore


@pytest.fixture
def client() -> TestClient:
    cfg = Config(
        telegram=TelegramConfig(token="x", admin_chat_id=42),
        api=APIConfig(enable=True, port=0, allowed_ips=[]),  # open for tests
        adapters={},
        defaults=DefaultsConfig(adapter="copilot"),
        session=SessionConfig(backend="memory"),
        logging=LoggingConfig(),
    )
    catalog = build_catalog(
        {},
        {"copilot": [ModelInfo(id="claude-opus-4.7", display_name="Claude Opus 4.7",
                               slash_alias="opus", provider="copilot")]},
    )
    ctx = BotContext(config=cfg, adapters={}, catalog=catalog,
                     sessions=SessionStore(backend="memory"))

    fake_bot = MagicMock()
    fake_msg = MagicMock(message_id=999)
    fake_bot.send_message = AsyncMock(return_value=fake_msg)

    app = build_app(ctx, bot=fake_bot)
    return TestClient(app)


def test_health(client):
    r = client.get("/health")
    assert r.status_code == 200
    assert r.json()["status"] == "ok"


def test_models(client):
    r = client.get("/models")
    assert r.status_code == 200
    data = r.json()
    assert any(m["alias"] == "opus" for m in data)
    assert all({"alias", "id", "provider", "display_name"} <= set(m) for m in data)


def test_send_uses_admin_chat_id(client):
    r = client.post("/send", json={"text": "hi"})
    assert r.status_code == 200
    body = r.json()
    assert body == {"ok": True, "message_id": 999}


def test_send_explicit_chat_id(client):
    r = client.post("/send", json={"text": "hi", "chat_id": 7})
    assert r.status_code == 200


def test_ip_gate_blocks_non_loopback():
    """allowed_ips=['127.0.0.1'] (the default) rejects TestClient's 'testclient' host."""
    cfg = Config(
        telegram=TelegramConfig(token="x", admin_chat_id=1),
        api=APIConfig(enable=True, port=0, allowed_ips=["127.0.0.1", "::1"]),
        adapters={},
        defaults=DefaultsConfig(adapter="copilot"),
        session=SessionConfig(backend="memory"),
        logging=LoggingConfig(),
    )
    catalog = build_catalog({}, {})
    ctx = BotContext(config=cfg, adapters={}, catalog=catalog,
                     sessions=SessionStore(backend="memory"))
    fake_bot = MagicMock()
    fake_bot.send_message = AsyncMock()
    app = build_app(ctx, bot=fake_bot)
    c = TestClient(app)
    r = c.get("/health")
    assert r.status_code == 403


def test_ip_gate_open_when_list_empty():
    """allowed_ips=[] disables the gate."""
    cfg = Config(
        telegram=TelegramConfig(token="x", admin_chat_id=1),
        api=APIConfig(enable=True, port=0, allowed_ips=[]),
        adapters={},
        defaults=DefaultsConfig(adapter="copilot"),
        session=SessionConfig(backend="memory"),
        logging=LoggingConfig(),
    )
    catalog = build_catalog({}, {})
    ctx = BotContext(config=cfg, adapters={}, catalog=catalog,
                     sessions=SessionStore(backend="memory"))
    fake_bot = MagicMock()
    fake_bot.send_message = AsyncMock()
    app = build_app(ctx, bot=fake_bot)
    c = TestClient(app)
    assert c.get("/health").status_code == 200


def test_openapi_schema_advertises_endpoints():
    """Swagger/OpenAPI schema is auto-generated by FastAPI."""
    cfg = Config(
        telegram=TelegramConfig(token="x", admin_chat_id=1),
        api=APIConfig(enable=True, port=0, allowed_ips=[]),
        adapters={},
        defaults=DefaultsConfig(adapter="copilot"),
        session=SessionConfig(backend="memory"),
        logging=LoggingConfig(),
    )
    catalog = build_catalog({}, {})
    ctx = BotContext(config=cfg, adapters={}, catalog=catalog,
                     sessions=SessionStore(backend="memory"))
    app = build_app(ctx, bot=MagicMock(send_message=AsyncMock()))
    c = TestClient(app)
    r = c.get("/openapi.json")
    assert r.status_code == 200
    paths = r.json()["paths"]
    assert "/health" in paths and "/models" in paths and "/send" in paths
